### ISSUE TITLE
Build

### ISSUE THREAD

**Issue by XimmersiveX** [IcePlugins/KillStreaks#1]
I'm still new to programming and don't understand how to build this. I downloaded the zip and opened the  .sln file which in turn opened VS 2015. I try to build it and I have 18 errors that actually don't make any since to me.

From what I understand of the code it really all looks to be in place but I'm wrong somewhere.

Could you build this and re upload it by chance?

**Comment by ExtraJuiceMan** [comment]
build available at https://github.com/IcePlugins/KillStreaks/releases

documentation available at https://plugins.cirno.pw/Killstreaks/
